### ISSUE TITLE
after publisher url changed, journal page gives 404

### ISSUE THREAD

**Issue by beyzakokcan** [ojs/ojs#1432]
A Journal of a publisher gives 404, after changing url of the publisher.

**Comment by hmert** [comment]
IMHO, it's about elastic indexing

**Comment by behramcelen** [comment]
it is so normal. if scenario is ;
 1 - enter an journal public page 
 2 - in new tab update journal 's publisher slug update
 3 - and refresh journal public page. And page gives 404.
Because you changed publishers slug.

**Comment by beyzakokcan** [comment]
how can we change publishers slug and update the journal's url without getting 404?

**Comment by behramcelen** [comment]
My scenario is;
 1. i enter an journal (behram.ojs.dev/journal)
 2. changed published slug from admin -> publishers -> edit ( behram -> behram1)
 3. refreshed journal 's page (behram.ojs.dev/journal) responded as 404 -> `so normal because we changed publishers slug`
 4. i entered new url (behram1.ojs.dev/journal) it responses correcly.
 5. i search journal an journal 's result link is correct

System is working correctly i am closing issue
